### ISSUE TITLE
Tasks for releasing the VDP project

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/community#186]
## Summery
Here we collect a list of tasks that needs to be completed to release the VDP project

#### Quick start example
- [x] instill-ai/community#181

#### Improve Documentation
- How VDP works
  - [x] instill-ai/vdp#52
  - [x] instill-ai/community#184
  - [x] instill-ai/community#183
- Quick start
  - [x] instill-ai/community#182

### Protobufs
- [x] https://github.com/instill-ai/protobufs/issues/8

### Protogen-go
- [x] https://github.com/instill-ai/protogen-go/issues/20
